### ISSUE TITLE
MVP2

### ISSUE THREAD

**Issue by super3** [super3/zmine#2]
### Todo
- [x] ReWrite server to use [Flypool](https://zcash.flypool.org/api/pool) instead
- [x] Add a linux binary miner, and get zmine working for you locally
- [ ] Window's 32 Bit Support
- [x] Error Handling
- [ ] Mac Support

**Comment by montyanderson** [comment]
Cool. I'll be able to spend an hour or so on this tomorrow, continuing Tuesday and Thursday.

**Comment by montyanderson** [comment]
Okay, so I've got it working on Linux - however it was messy... really messy.

After installing the miner in the same fashion as it's windows equivalent, it threw an error about not having the shared nvidia library; I thought fine and ran:

``` 
# apt-get install libnvidia-384
```

It got further, but I got this error

```
error while loading shared libraries: libnvidia-fatbinaryloader.so.384.111: cannot open shared object file: No such file or directory
```

I found tried installing different driver versions, until I found `libnvidia-fatbinaryloader.so.384.111` in `/usr/lib/nvidia-384` - I tried creating symlinks to no avail, ultimately trying:

```
# cp /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.111 /usr/lib/
```

**Comment by montyanderson** [comment]
I'm just starting to implement Flypool usage - the API says `Access to the API is limited to 100 requests / 15 minutes / ip`.

**Comment by super3** [comment]
From what I remember it displays miners all on one page. If we poll once a
minute then we should be way below the limit. Unlike the other pool the API
responses seem to be consistent.

Do you have access to Mac?

Thanks,
Shawn

**Comment by super3** [comment]
Moving this to #9
